variables:
  REPO_NAME: codeberg.org/librarian/librarian
  DOCKER_HOST: tcp://docker:2375

stages:
  - build
  - deploy

test:
  stage: test
  needs: []
  image: golang:latest
  script:
    - mkdir -p $GOPATH/src/$(dirname $REPO_NAME)
    - ln -svf $CI_PROJECT_DIR $GOPATH/src/$REPO_NAME
    - cd $GOPATH/src/$REPO_NAME
    - go test $(go list ./...)

bin:
  stage: build
  needs: []
  image: golang:latest
  script:
    - mkdir -p $GOPATH/src/$(dirname $REPO_NAME)
    - ln -svf $CI_PROJECT_DIR $GOPATH/src/$REPO_NAME
    - cd $GOPATH/src/$REPO_NAME
    - CGO_ENABLED=0 go build -o $CI_PROJECT_DIR/librarian-linux-amd64
    - CGO_ENABLED=0 GOARCH=arm64 GOOS=linux go build -o $CI_PROJECT_DIR/librarian-linux-arm64
  artifacts:
    paths:
        - librarian-linux-amd64
        - librarian-linux-arm64

docker:
  image: docker:20
  stage: build
  services:
    - name: docker:20-dind
      command: ["--experimental"]
  needs: []
  before_script:
    - mkdir -p ~/.docker/cli-plugins
    - wget -O ~/.docker/cli-plugins/docker-buildx https://github.com/docker/buildx/releases/download/v0.8.1/buildx-v0.8.1.linux-amd64
    - chmod +x ~/.docker/cli-plugins/docker-buildx
    - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
  script:
    - docker login -u $DOCKER_USERNAME -p $DOCKER_ACCESS_TOKEN
    - docker context create mybuilder
    - docker buildx create --use --name mybuilder mybuilder
    - docker buildx build --platform linux/amd64,linux/arm64 --push -t nineteengladespool/librarian:latest .

deploy:
  image: alpine:latest
  stage: deploy
  needs: [ "bin" ]
  before_script:
    - apk update && apk --no-cache add curl git
    - wget -O - https://fly.io/install.sh | sh
    - git clone https://codeberg.org/video-prize-ranch/fly-cfg
    - cd fly-cfg/librarian
  script:
    - /root/.fly/bin/flyctl deploy --no-cache --detach