version: '3'

services:
  librarian:
    build: .
    # image: nineteengladespool/librarian:latest # Uncomment to use image
    ports:
      - 3000:3000
    volumes:
      - ./data/config.yml:/app/config.yml
    restart: unless-stopped
