version: '3'

services:
  librarian:
    # build: . Uncomment to build from source
    image: nineteengladespool/librarian
    ports:
      - 3000:3000
    volumes:
      - ./config.yml:/app/config.yml
    restart: always
