pipeline:
  build:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      dockerfile: Dockerfile
      registry: https://codeberg.org/v2
      repo: codeberg.org/librarian/librarian
      platforms: linux/amd64,linux/arm64
      tag: latest
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    secrets: [docker_username, docker_password]